    name: nolop-printers 
    channels:
      - defaults
      - conda-forge
    dependencies:
      - python=3.13
      - pip
      - Django=5.2.8
      - requests
      - gunicorn==22.0.0
      - whitenoise==6.11.0
      - pip:
        - PrusaLinkPy==2.2.1
        - python-dotenv==1.2.1
