# Generated by Django 5.2.8 on 2025-12-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(choices=[('core_one', 'Prusa Core One'), ('mk4', 'Original Prusa MK4')], max_length=255)),
                ('host', models.GenericIPAddressField()),
                ('api_key', models.CharField(max_length=128)),
                ('date_added', models.DateField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('staff_notes', models.TextField()),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('curr_status', models.CharField(choices=[('operational', 'Operational'), ('paused', 'Paused'), ('printing', 'Printing'), ('error', 'Error'), ('ready', 'Ready'), ('busy', 'Busy')], max_length=255)),
                ('total_print_count', models.PositiveIntegerField(blank=True, null=True)),
                ('successful_prints', models.PositiveIntegerField(blank=True, null=True)),
                ('printing_uptime', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Printers',
            },
        ),
    ]
