# Generated by Django 5.2.8 on 2025-12-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printers',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
