# Generated by Django 5.2.8 on 2025-12-11 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0002_alter_printers_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printers',
            name='curr_status',
        ),
    ]
