# Generated by Django 4.1 on 2025-12-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0003_remove_printers_curr_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='printers',
            name='last_job_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='printers',
            name='model',
            field=models.CharField(choices=[('core_one', 'Prusa Core One'), ('mk4', 'Original Prusa MK4')], max_length=128),
        ),
        migrations.AlterField(
            model_name='printers',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='printers',
            name='slug',
            field=models.SlugField(max_length=64, unique=True),
        ),
    ]
