# Generated by Django 5.2.8 on 2025-12-22 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0004_printers_last_job_id_alter_printers_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printers',
            name='filament_usage_cm3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printers',
            name='filament_usage_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printers',
            name='filament_usage_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PendingJobUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_path', models.CharField(max_length=255)),
                ('filament_mm', models.FloatField(blank=True, null=True)),
                ('filament_g', models.FloatField(blank=True, null=True)),
                ('filament_cm3', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_jobs', to='printers.printers')),
            ],
        ),
    ]
