# Generated by Django 6.0.6 on 2026-07-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0005_printers_filament_usage_cm3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendingjobusage',
            options={'verbose_name_plural': "Pending Jobs' Usage"},
        ),
        migrations.AddField(
            model_name='printers',
            name='last_failure_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
