blank_issues_enabled: true
contact_links:
  - name: Contributing guidelines
    url: https://github.com/tufts-nolop/prusa-printer-manager/blob/main/CONTRIBUTING.md
    about: Please read this before opening an issue (issues must be about website functionality).